---
apiVersion: v1
kind: Service
metadata:
  name: d3os-gateway
  labels:
    app: d3os-gateway
spec:
  selector:
    app: d3os-gateway
  type: NodePort
  ports:
    - name: gateway
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: d3os-gateway
  name: d3os-gateway
subjects:
  - kind: ServiceAccount
    name: d3os-gateway
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d3os-gateway

---
apiVersion: rbac.authorization.k8s.io/v1 # api的version
kind: ClusterRole # 类型
metadata:
  name: d3os-gateway
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: d3os-gateway
  namespace: default
  labels:
    name: d3os-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d3os-gateway
  labels:
    app: d3os-gateway
    need-metrics-collect: ok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d3os-gateway
  template:
    metadata:
      labels:
        app: d3os-gateway
    spec:
      containers:
        - name: d3os-gateway
          image: registry.cn-hangzhou.aliyuncs.com/draven_yyz/d3os-gateway:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      serviceAccountName: d3os-gateway
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime
